/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package devicesim;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.geom.AffineTransform;
import java.awt.geom.Point2D;
import java.util.ArrayList;

/**
 *
 * @author erhannis
 */
public class PanelDisplay extends javax.swing.JPanel {
    public AffineTransform at = new AffineTransform();
    {
      at.translate(40, 40);
      at.preConcatenate(AffineTransform.getScaleInstance(4, 4));
    }
    
    public ArrayList<Point2D> points = new ArrayList<Point2D>();
    
    public boolean skipRender = false;
    
    public final Font FONT = new Font("Monospaced", 0, 14);
    
    @Override
    protected void paintComponent(Graphics g0) {
      if (skipRender) {
        return;
      }
      super.paintComponent(g0); //To change body of generated methods, choose Tools | Templates.
      Graphics2D g = (Graphics2D)g0;
      g.setFont(FONT);
      g.setStroke(new BasicStroke(0));
      AffineTransform saveAT = g.getTransform();
      g.transform(at);
      
      //TODO Render
      g.draw(new Rectangle.Double(-20, -10, 40, 20));
      g.draw(new Rectangle.Double(-0.02, -0.01, 0.04, 0.02));
      
      g.setTransform(saveAT);
    }
  
  /**
   * Creates new form PanelDisplay
   */
  public PanelDisplay() {
    initComponents();
    this.setBackground(Color.WHITE);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    addMouseWheelListener(new java.awt.event.MouseWheelListener() {
      public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
        formMouseWheelMoved(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
    double scale = Math.pow(1.1, -evt.getPreciseWheelRotation());
    at.preConcatenate(AffineTransform.getTranslateInstance(-evt.getX(), -evt.getY()));
    at.preConcatenate(AffineTransform.getScaleInstance(scale, scale));
    at.preConcatenate(AffineTransform.getTranslateInstance(evt.getX(), evt.getY()));
    repaint();
  }//GEN-LAST:event_formMouseWheelMoved


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
